---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata
  namespace: airflow
spec:
  encryptedData:
    connection: AgAd+dL60F4ONX71CU8K/j9qgZqJtBZmL1xdbfO/91s0i73SyQAcJxE+5ZZyxPnd21f5I7zBFdmNJYxozzLme9M0HM6iuAW7SxuZuSb+0L1bCxiZDRE5zDjFtDQrOS7N03zTlrl1lI3z72CX6OjKHkfeJDUEwvmWq3/Rlyvu9k44I1CWOJqFU3KzwwuRxI16mmMRlw+mMiVL3LdZ5SOg4gpA6mtdeiZynKSBahh7rS6MgOYM8P3Rw9NXlVCkUJVemZ94ofhQZC4R53eGLbSO78U3Y4suomldqAUHMlN0MXpMyD2/FsXpnZ1lsoweEECelK4z2CXLPTnKySRL9V44DBAk3EpvpaKotH3WDGWPldqKtBFiiUL0zznmei0EYjbG+Lkw4szbLhor+jWICSLW1gYfpy+wNC16MNxO1u3gq4THRLuhOWcJxms2GL1plqlJ3Q5iKjVTci5q5H4hjD8GgrCj6LIekyPnfuTfxwDej/FvixjXjr1vCSa3QuwL7emnQ0GEq2Kt1DGokp4Nd2mVGHxhKMLbxzaAecofUMsfYoTiT0JeIxwoeb2RNLgv9VeixU0inx9zBZY/MWuZE13R1OpNupST4nBjF6JZRobXUBTfFzFeTj2a15sAQoUx0fIECxGeGBfHBZO1lddiyEWlSMd5qvXaUSrPXc7oLE1TXcFyEW7xsUKL0xzMpaHbNqudmRecZF8Vq2NFZ1zIzPQmAktVAe5e2KdA0rM4woQVGYDybrc8ZbX4afHLvt1rvce46HJk/TaHLtqqH9liLwRII0A2TaH/kN3SseVjUIsQb3mZHiPdrhNhnbJ1mw==
  template:
    metadata:
      name: airflow-metadata
      namespace: airflow
