---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-airflow-user
  namespace: minio
spec:
  encryptedData:
    accessKey: AgB/oevRbaS9/2F7aORoadtTFQkAVcriQSMHzIeHLvkeCKulvfWvrpeJew6EBlpmKU3wWJGjBmZTTQfOg0tcaF7pkmN0hmsDAOogBjHEVJ/i75jG40Fbv1D5Fz6H8A4OJVVph8CheZ63kcE95+GivV5Y2ucnjlErWhEgNIkUhGlivmkp27U6pt7WcOWkeuBnjCdJrr3Tp6jVgAP9f9RddTGuiueqIjTX/tHyYZii6u96wdC3LPrLvPU9X5xANERQyzO0XO55gZ7M994DY8oh19/+4hJksAgz2jqX0kvfcuS5nyHesRBBF8a3mSwC3tw+FM2zn49QhDdIMDZruHUd6onkbf79YzFudpXFR3Mao9b818FTfUlvenB8bBjF+UXaMPzmk3U9l4f85YRG12+wvcQ1puDQfZPGsSbDDp2hv4s/w8MqJky7I3yPHgrN48hfM2omgPquMLGH8RcaE7RYTtINZ3gPbS5MrdMVR9c1gKRaC6xWO2YXY9bzZ+LKM1SrHfTWH6GJ5kXBhQ8R+o9ghrcQGoxG87/+BLwpo/0yNBLhQEMZU5Xq8PhMAL3+u4+9Lerm2e4TQi2y4iX8EX8U3D0lsmUXnDpk+Y0AhcC7qQU4oTjTYfRhXGZbsNLAEgdf9C8cg87RoJ/uKYWm9IAp92HTpBAXy/aY5+x9tFAKKL16x1JV1Bykz5DojqYok0/U/P7HnEz+aNUI
    secretKey: AgB72B72nmF8If7oz3EbzZ2TOsfu5I1/BreyFPINUmMFXUpOJR02B/2/bX5zq7Kib7ZRXIP7T5+W5rFSiNj0w8QNh6Rvt2zOxo0P/Gepp/8GQt9UQRwpKRK9jea0HP40TD1bWdEeMqDYh2ThfB7lV7U7PBHJ6bPM9SxoVGIWjb1DE64fbN+ooDALFd3eXe548IUhUHXK6/zuKrmOvUSRHWlHFtLjNyNnMBwdcHNyWf/7sS7gyQC1ishDkt/WMNa2vqfp9LJIKxDXR9IerNTanKXJYYcT/owZegxg1qzUY72WbZuiw5AfPNSsUvXClKGB+XOfSdqR3FJZNxVH8lGWzsXqtNhSMnVEKDSR5y6DAIBYyyMyDLRkprOjsCRD9h0l7xOfd76CCey2Rc5PeamS3v/hYZByAtw1rLjxUWe/fxxOhBerSSNL+R/Z7x5Soq3FsheYWWYqB2AApekhLCJaxL0cXd8qDOE9LgR9pQm2TcymlsuXuwa3CJpxe7ih5ocTQkO7kjgh7ZAFxW5YvH+iRf4HPucm2irrtbj9nH/rKJwekcHhNZnu0wpdtEj6+Wk6QAtM9sX2yj2m8SPQRxchANmChkyO9bO90QiHU+acXHvdDfjh23WgDlbkGmbQbdWAeQGOGIyPOE5TEGdyGsyQ9as03tp2Zfv+hEEy7s3veslkc4Pvl52qCCQKg8sPODsQ0e/yt4kLlWIb/wOk7T3NYI1Hy50=
  template:
    metadata:
      name: minio-airflow-user
      namespace: minio
