---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-airflow-user
  namespace: minio
spec:
  encryptedData:
    accessKey: AgCDBqN3qH9yJr4Ui36e+tgmmTUtarW+agl1ProlXO0SsRJKvP/Z1Cmcq5zZGUHlgvgMJVP51CLD7n3eco92pmFZ7yu1QIrqpj2pqf6PfEfp1hPaMzW2VLxD5b5S1OSmpA+pLry12xTgYXuGy1dkDd9Qg6zB4sfetWt6JydEBHezziXwkfyoaImv664eZPm0A3ftYFJ5q6lus5I3v/cnUz72lR/Ut/DNoGm63meOAwvWZUdohTvzv1j1yddoSeu5bDfjneQvHnLipixURjYc95fofpITrbCAPpEgAPBh+lPDUs+mXEgevDZZ95R1VioPbyPK+RCHn3zjCRlwfq+dnT22VXqkcRC6+mfDXKgvfqhHQwd89ZqEzyIaT/cY7nF1q7MzsXI1sxe6c/gIoANhTjnAGdq7LIdAJnCS3SqfWwRVJD+wr3Hk+Eo+5NuiB6TR92ck3+EqdK7iRzUIR4X8hWtJy7asxB9W15DV0a2VaxtDetfYN8MWjChABjn2tmHk7FB0edLKEX4vDQq59YsM4DIeSTtaYooG2wS5FMQe4SicZduxWsqcJFxPpPArnzF7L84RT/UuDV8l6OYT2+A6YGry6/KpbCId+ZkQxKUppqdUWs3qRIIC3Ijfe9oriHsTjNwRvJStL7W2u+EytBZpkXQ+isNhWxju6QjrsDEbyi+xHwF2tavBrgyT8I6ZCs+gNOLHVohTl7bS
    secretKey: AgBDhd7vuRDGSIhP0dj86rz+gY8ouvrptz3JRB7Ba0KTnFl77SEwISwok23gnvPJSXo8C0Xxe7c6Z+FNq0wDKHA+4dfTOt1zfBbt1BiiZAOZR1tMbUGb4rIs6q32baU8xcKC5ccHfDlapleyR6kr9GY/ooFPPLT9SW1XXA9OOBCXrpaEYcoQ/4uEjgdXL8amCzluTarc36F3jkdHBrPPdZyWD60OkoxqgvZRCkLo9Qe2NF9MeKGyXWGMN6Qxa8Y8CR6pjN+n1e8JP33Ols07bi1jpUVTAVMYaBml8AOR859rRJxYqwf/R/vRWR2rr80HerkWzV1caaixg8OUKmRDXwAFiAcQDIYhZxvLMZ918J2xJXBVFNMR6S31/oCn1wKGKYnEi0eZMMYB8ZgPK9ojxaoR2mCp0HT4ma6WTdg/Q9DdHsgp4w5WROgHNGqr2vXw8Nz0ZdgJtIV+Cmo8JIjThi0noZHB7FcDL83UfhIihRkB2nF61gEWBxhhgpuH5l6zVs1ggbCiDA/YysvmcItx8CBLG7usf8jt0o3DGhqfly7dLLLsoWoZF3VdAluM6Wc/JO6EBaC/stSI29jAPbfp6sfE/I+2NHLOYr5b7a0Uauh0a6pcaGu/bimDP9Ga64pn+KC1SWqNKHWzO1vIIxmBiZZdcYdHETxiOOn4BkT7Ok5FzL8hvDZpz/22qUc8yfXM35wU233D4+2JZ3KFGH0Dygjg9ok=
  template:
    metadata:
      name: minio-airflow-user
      namespace: minio
