---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-mlflow-user
  namespace: minio
spec:
  encryptedData:
    accessKey: AgCrFgvpl43G9ZmvWXdmbM+ERljF4FF4xPsLvH6eX5197ZWknRQRfAE5zqLA3D58XmsK4t+V9MOg3XB/OI0sZkzHgGXXkDr3tpURL863g8KS8QsqklJ1hljnnr55G3e+Jrb8Kt02Xhz4/H1Drteg30ZDh6kjypE7nEQ1HyCeLtqocnZ27mB6WXuya8cHdNB4+zsG+a4n5nRLulAWrOh5n+QF6A2cNw6Z4cJR1PmR6oLfeqoS8mF4tiP133UOXx3/u5Am8dBMqUhn/4M32Yi8a1hBUDjTLJYtq9WEvLlLK+9GTZQm6LEHaEw94xuSy/x7Y8ArNSm7qDga+q3YMeGa+/92rhxKgqvqvme9aj6l4NIlqHKd1YlAKYoclltMPSKZfv95TqmHWUUQ2dWRxG1b/DsjsWAebXCjJFo4/MxAxhbLI+JHes3+ylLAp0jznLjnu+TvkE5X0qmGNaG/RtH4CX3FKAnFxEQi0e67Ua+7yygH3d1zzeuUbgH1yKvbrJEPPT5qNs7rTma7iG9UybH4BYj9f/40uH/FvXPB+4PhtUFUBUoUQmMrwuprKf2Jgaql9XITEtDzEquCGMELe7LxzC7ACTB+wFYy8UIbdKdQ2IhGdVWQyOFVkwl33QyXbStLgwovh/J25xgW2nghfAVwKlZOJ6Axz70f83UVekh34hWlCaAnGHPCteeHBZ7dq64iULgsA6IooAA=
    secretKey: AgA+ynApBamKgaPGSUrjwk8OJ+3fv37IbXpPdTjeg0dJTGZ1HebEqTpYAbIkzHXOa22f0XXKC0NKQMfwiCT47wsOJ+i7yePJ4ahlokR+jtrdF8eDf8N0DFAfK4iSrkkxSkKhXT17cGjeIT/CCiBs/YJUGYcJQz7MQsGVS9bnrw4j7GybFRFzg7GiwPAg3VtXfoOnU2ixPRVkqwc3UkN9mW7M59IAruTMsS1w7Bgo2Op7cPuh5sUum4QSip+PNaDZ2DCevGRYOMe9zoaMLSUzEybWAU+UlNAuwGMovkxs+CqyGkLVu2hyt4o96JaaNG+sELuBLTgro2cDxkspYikDE0JVzgYdS2emD6CVWg/eC14yCNT5F66guDG9nzjlEmiLEkeC5vmbAMMwPsVRTk6WaERHEMfgqhfWrjPSdim67Vf3b9Owc8C2S8uCcB/+dTQDFOOxqxiKKiM307Svu+CFTECPsBSldSFUpOUD9sTGV4nYMFMrdaofiOfdFTf4pza3ks1eW7oDAFlpUojpk8O8Xz8rEfwX7xTY6eqrNkb38HVPhceaJJ2y82lR2Hg2fPZ+yDFN7jvcfRx7Gk8O/j263VuazlQ+GXKopE8XI45A4fNRQhOhTEtPx+VNRyk29mWoM3DOHi/ut8OB4dnSeyj/P1bPCPCdR/+xQvc66lzI8yHQ79lZ8WfNltba8Tx+uFuXTDzYWrgwi+2lwDku0lbKmEbXN7w=
  template:
    metadata:
      name: minio-mlflow-user
      namespace: minio
