---
# ClusterSecretStore for Kubernetes secrets backend (bootstrap)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend
spec:
  provider:
    kubernetes:
      remoteNamespace: mlworkbench
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
