---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "minio-console"
    tailscale.com/tags: "tag:k8s"
spec:
  ports:
    - name: http
      port: 9001
      targetPort: 9001
  selector:
    app: minio
