---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: databases
spec:
  encryptedData:
    password: AgDOLCfs1Nc0qfc56zqcAVgF2JuwtLk+WjVPBEDT/e/SRGwXzBjxH0NrsPzWNWKPp/ZA1yN4Gvpw3PtUhDIOkjosBNG4RNV3RyePD8XTdxJTpv/JBoS+ubZZIkXhBI96+XdwtupDuBPOGTPqQMWGGO/wO85cnjzN3hlY9bmI2U2RCMAo7vvZImn5pbs3wG97maPI/Ur7W/D6jYnkd+QH9czkmXVF11xKtOd95sNVz4OFxCMG6l8HRDUr7eGjwjddKmSoQsu4piXRgLTeMH9DMYUBv8RPZ6zLlh/PY4mr7Yr///esIWYNBSRH5mvIKjqaIHm77qUmLVUxOgbnXY+glOWneAymqY8sV3JiwbKCS46kQnnF6fdom8k4OeRmqbrhlbzXVRWejvzPVw5DEBf7mEB/RtLP/Z/1CtmULCw+XNp932WH4Od9RIKrJkAMKc0HSQaRh6dXwc8dyLjfLGN8zNpsqPJfnBV9metfaANtSIRdD1xnHlykrSF/8uviBXrXo6jyOiuh20KlDr35Nyw0JNeqyDe12HNY6GLMzwYSEt0g6PMtSH1sjfzx/xx1T7QuESA8O9v8kuu/2nNEhOIB5KIvB9b/bONm6gMmvoMkq2aDBdk03l4WiZcraE5mEEYPDr30c0sDML8Db7G5NlGAwD8w9+lcABMdJF+WDdNoldjgKCGroy7mUYfYRNGnQQuysvtOfnI26825TiKB2jWm/jKSzdw=
    postgres-password: AgCTo/XiffWN5Y9A+EEhhZKWdEXMcJQjILXqUEluq16GySi/bipem5rdFXUEgjc3mBBgdUCaHm41ryracRD6TiaPkUiSbEKNg3J7pvJ80HcGSQ2WUKE3QTVq7Dgfp43cB3QDQ/jtlGgT251p2Syu5J9b9US96BSGO+fbFpud3eFf83flxh/kS3klKElPmlN1lk88/fsppkQAjeB38FaNrpQoCeVN8io/WtjlT6njuDNHQDFAO5annmmNUMuFpQ+vT6VuBiGk5A5pQexF6NRIIkBFX6WF2sz4oKcrFl7HLXd578Jfqtamec1zqeu7TetTFBKv1lxprNaWinBsjj6Mpl1vjLJyWv+Es5TwCWr38TIkIAoaXhy/iNynrNoqHRYqDoyAHOwOQrr5DLJxDN5H6YM31zw42Y5D85KnWVqJTMB9iY2If7WjqLLeSf4jMf6MbaS9P8EhBIFzwAcgKLdFPb0mij+AjteCPbJKKZDFwCWujzYXpF7mqgzvHjKtitUTtcpYZ7gy1VO0rSOQCR+T+Yc4wHt/CgXMzm9nwwBQYH/4WzhVl+4uARDZpnewVdC8P3EPsp055hrkVRlJROfL9UD+tI84bauX/GcyhM5vPV/lfu2R9Pjb9jontIbdadxt8ruSTlQ2iA8hKqocCFF7KD1KQMsVdPx+hK3RjYAOHAjvzaY+zXBaAryfyXUKzKpxg2nRZouHwwxgf6iwryj0vNsKLYc=
  template:
    metadata:
      name: postgresql
      namespace: databases
