---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: databases
spec:
  encryptedData:
    password: AgA/4xF9/QIjuA4orGJjBOoZbnTAglo8487P68/4D/NswR5vFBwhTI3SzXSepuKy6qWQl5n5jIzXKlpByBF6ka1+wRaaixqJx6MgHkFj5pQIy2y4QY3qRMYPudsQTRKOCk4v3qKsRK1O64Rj4BXY56iv8bksNVkgTnEgLNUq3e8Yi/tCq7kxUdmwh4oI60Cc/Qrm89scUJeOqS7HF7iuNDQdmpBnkavkmmOBOcdTCrO4st0jYd7MxCZXtS9nNEXAy8cAWvebtRbOTFlJe2paUZm6SGHtQOYvndmDCe0fyg17L+5ix5dgjvmvez/thIowQg8I5QFjpvF5nC0T407N4lWRsoKQ3hEfMuottXmXoa1QpoWZmM/2anFlwInCu8KYadQ2Rwb0Q5fG5K4SYHnkREI1X2sta4KoZqCfwJPCChji1jjPvnAq1X8YvpqsKiPyUN0psHQtK9jVw9/XWwgnoCPQ/2sDS91cGHDVvDcw1bt21y2+iceFzomOCuWisPLC7y61NGU9wFjuYVjypfymx6O2Iy99lOlGHwZ4dcI6T+TZx+XJnLNG5nOIw1CjxBkq7NrsdtPRU+9zjiy4ABjurHmrAP0Rc3PLTqHyI+xkabuT1gacjBcIzez1n/DUkBfd740p8VMyHu8XEV82Nfb9IkxMfe0qM1kx+FzgNNBnNlK2ZyQlZp+KMwYnHuqnzKs9DIUOcbwcYXwG7Hv/m90i/t4Jgeo=
    postgres-password: AgCAB+d+fPdeZV6PIxOm4FMaJswoMfwNwKFoGbJaUBg8x8Y6OqZKITdAHKOUIFq+d0bFFEfrPHFJQ4M1zs9g9M9+M/CUrMQeyZdiBInoPrB+YXhP8ezmx71MyEqiNcCxo4A7Qmkmcx3zEDMzQovjCI9EV1lF00jotJOjDTOSpX8BaPFOYQM16Gge4iLTYuvB9ABDK3N6bz8zjQ+ZSPm+vI+k31u+yjpW4Ur1/jKD7lP8KFctiaC2cVEzN5eN4KtqnrOZJDewnwWaydy/BcDAy9JiCg3xmjSMmkpG0yOBHMt0CiI0/O8BciAp393q/qx91SgGm+0X00EbKfPXfJI7FUTYj0EZJ7tmQVIm1ikImQarLdmv3qgz5GlB8xOWGGfWXXU4v3fuwrV20ciQpDqN1HzmYxc5BsIJf8W0pKUAXaXJHLQJKYR7beik5PNSxYeA6W0J+r7vDc/CBahfhyrGAjO7lM5GXpZM+KzqJcatepPCCUQ/qIHrTcuAOrbUQlsqJV0Y4JnNFij1VU/72/LB+l3c69v+LW5HnZ+P5d001NuNDZHSw1j3zVzm3eeHQ/qvcRW7o3vpp7GlpS1d37L76pFcRmURivt7R2QcWii2r6dOV2UNGiaEcUTVCgdGxWqoWY7Hzk44TcBm/RSCxETL04+zXLdP996LTF53CuYLD3TGuU1htM6xoKv+zLeN6XktENd/IdACGxr7JwyimTSDYiufrYo=
  template:
    metadata:
      name: postgresql
      namespace: databases
