---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-mlworkbench-user
  namespace: databases
spec:
  encryptedData:
    password: AgA+8dd3sqjFPCf9a7yAKKRyZ+hKYTZjnI6yCQ76qomBCbYLkSRiTOT9v5qMxegA1jlQMQoYirHMDPJefikIfWusqcfFEsww0MvjEJzXEoSaG9V9IpUPVFjLo+CLVcHzf6WIOwcH1AkD0PmhVeEPAwVnrW3+tFIlv7s+xPKrPAx5CbBYHDjKK1tgEoONxpwo74hcWATNh7f77e8EOS2rRa+QNXHDCpA00sh6figd/jKrRHk53SHgr0XWYAn4BdQtgbNVPEGEjm4FdPGCNPXv3dSAvff9tbr9+PAaG4cuAiAtg/1MhHeSHquT4s/IHzAutL+AsEFuIb8HTVdb7EX6iiJaLAmvN6Eef5TdfxdFdDZJ38XhacONj1whVhTmFxpnjqlgOVDgAH2txWp/voVAXtZ7OhKMLKsKmcqJ1gqklSe2Z7ta0TKmP5xeXFCL7V4y5gK9xRC6edMM7DCR9UkO7Dxv8n5+KjzalliLjG8PgOm9SBxy3H3+sAQMA8vx7g0Gsq6DE9PNYfGpvGRaJEy+0OXL+sLJfatH/U2DPGVgQPUxsctBRGm4abt18yfmU1s6TV2RkWImvQTnDl3RJ72p1pLeJfGViTN8ucCwiMz9iugeUGA7cRPgL/vKEFYC+PCjNMXA3cd+1JHt6BQ4j6wbqB/e8K4gKxqKWd6m4oFNXKr8usx9TAKchguvwrbQepZS1aJJL4v4rTaqtWjQnLk6VRTgNXY=
    username: AgCfcf9QX40O731pn0Fnj8Sok39mED3FNG6E2D5qX0LbcL6PDLMUmADPcqotvqvS3KRBgML/X2chrtWz0K7ZdcpbL22Ui4vH0GQf/1AJjSuxlCWHojIZhFnB+q3aOJ0eQhi28Jh4ntlvPltg9QMtGonWCHy3Tzg04pCNZBQ4pzXk4X59vOUHtrMj6SqXmaASJcBnHcyMpHxMqkYHLyS19iPCBbjDJwhFvbrfhz3i5Cd3pa1SBgR374+HydJ5U6qAHg0h+s9ZdkGDsADDXnoNZPXGzLrz35pta3GFyn6L4B2iyamAnBzp4hSiGcMWTOMOMboVoVsqyZpJn4PLunh88xAc+RyxfsCDL2YXEWRsA0LDZkKoAcMfFd6LWwviTbMh40pihN98f7M3dE6Dk9EjKK+aIJ4eTdg87gNqrgIbrLEGRPDysRRVgQK8WxybBDEBDW1u4wsu8D4xkjA6ZURuf58ZNz0O8tDz6IPM8tEmxCFtay3EQ4G9/XvR0NsdvHXWBj8SzZ/E+0IDUpySIHPgPeNIg7+FerTriYRabRoNq8Yx2pPmptSjWaPAB/vgrw6L8wytNwv/0DLQWRQeqtGzivnNFUXxnb95h1Su37JchcjbRt4NyfX1yPOsVAF8pX3FQLiuBary8/fNjazRV8NZSF75eyudw0aTnDZJxy3ltebrScIY9lUAw8DSuNv2SKnXZsrtaxvDggzlUeoTgQ==
  template:
    metadata:
      name: postgresql-mlworkbench-user
      namespace: databases
