---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-airflow-user
  namespace: databases
spec:
  encryptedData:
    password: AgDH1eUza7gqhjQn5e9kUw6p7fkeCsY7REXjgHuqanJs0yot0beH5YUIv6Cxpw+734or+XXrCuXuoXxXzNialJeCwUtiI6QabbwwazrXVX6fDT4CSPzAvYNqp9OpEnndvQVHL/MOkqejozrracbs1VrdcdoSC/a4vYafqQcEbHfx7Atpa2Y2u6r0IvWB2M6R+0QkJs3DPJR3eJDtFuH56gZSiEIDvgl4chIvvSzAJBkVDb7qMWuJtqlr3TUzvL7mXsll7yc7kV/1JL/Ea/wJaCGsLo+mELri16vv4BFFi6jrv6wG28EQjvHVsm1BZAYnS1qTgIK/VvLyrPITUjCPEPzSBiJMWPhE1xWEQ/kX85dV9KPzcdX+UaYyz5vByAmBAIh9DNE1XIIreC9B70MVS+UqY2/Rxt6JPi6XwDMU0SP8Yp07cbL9xsddluPh1ZXh6jx71KIOhYHIOsviHNBsihSUOKhDWRFKw0rgHbo2jUthv/OnAAkjwjYwL7op+BarwSf8JKO6ixPEf2pG8HGPhRvN1jZ44LVUMKaqu1wAVbPYybIbSWBd/DGyhmabXB+1iJLc3ncCq54S9F7QxMeUXrXS0sgeioA3YNwk/JMHBYnfFImvlc1xzBbrTAcp+kO74MQpq3Dr1F5Y7tKxElnxWHSTEEKhhR0wvu5Xz1kxeu4NW8CM00K2rQNtFV/G8XbsV5g546yHENr9kWuFJwnOFJHuD8w=
    username: AgBeaNc1LB5AIFI5WzoR8ym6V6cO39oTT7mfa1o/fxweG8hpbUW9SFfc9RNEJ/vj5gUBGJe9JthSpLR9wAP1PnXGpf2qVwvEFTyr8+k0AvEAmg8+nyS6n87YJKHDBGn5ZRh6qBmqDvvx7ZrvcuBfpN9D8bLPUbCmimrcbs9fAAfIjSkbVOx8fKKlilqMyWuVqTzS+ZdQxQQTiIIV8h8IK89/jN1J0LyVBMRkvA+GXLtbMSQMlVqoqI4EmYY0dVt3uS8x+e3kFeOT3NgAqezVDKFerQubVAw1YtOiwiO6vvgJCjsPwlgoRM3n8LrkmTcwYFL/7NWrqOl5iOZ01eW0CKfz7VGBdE0Ux8MdTsWWxHfJs66+g8bAn2MDj8g6Vkv23rxyPNhlr3b2o2c07RuXkynnR2gKIAI5edDlLqaHMuBzEQsHvPgKYcxVSXBlOqlGnQIepVC8w/8PffSGDv0TH+n0ty11fD43ARbUo6B4mXazeQy0VJrkkz1/MgcKXlLzSv+TfiRcf04JYvGfdmLeUVE8DTLOSseHkg7itjaeEPkxFQkfaZnswc2Z/OYfn5+Kwnon3oUjuha0ABFhPVspIKfWAGCCHxUkdvUmD8MLe3I88ZA00OLAr3IMyop3ULGe0dvRM6jfGgGkSUNhdLEpJ2+6BEecSaj9wOOm79kbnRa4Xcjh0sUZphKEb1fpi1haCFkGehkIQktx
  template:
    metadata:
      name: postgresql-airflow-user
      namespace: databases
