---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-mlflow-user
  namespace: databases
spec:
  encryptedData:
    password: AgAOKA/TmxfTAnKbQlj4GAPBCmFcJ1kjLcsu3Ll9nG1FMophE2TgjneWKsgu/bnBGwKd4GKwqRF3JEAd9fa2VOb9aTG0Q/N4wjvgqg1HSYN28AREtUDJf6AUyoNBonTscg1Btdrr1z5+uTDFGR0pYdFCehWBhgGONy5z20yNAhJdny0OWbDt1XApn5HZ9WNL15v8jxNDgWOzAxUV8MprN+7SSAbz23iqFQNwa9FS2noPMAm99MiGsEzyHVP4/qXgh52Sv4GF3tCisxOiJSzrNCPPzD2BGx2yfOvxkzaJp4NlSizMnnG2+wa9VW9pBPBPPnnWORqFcyq69Fk2HZ1xZemRJD1yQXlikBYC36/okX5wCvRs80GMQ2PLRBQ0MhIT/kowt2GzSTmwHRBuJ5XWRHUEWjSCPo+o7BeA26AEj0PamUw5Vvb6Gr+yhJ1XFspjZwMiDYl5i7V4Tf5pB4Vn3DISDEMBSFoxeFhTvze3LRfpz0N7alyMR+FukLGnOLssQlqvfFXEK1uWmXU4n0/HDiM4PxSfx8ku+pKf/Tt7O0Q3po2C5gdEXoKpBLEIFvDAICSLp39yPc1zAguI/kqqk7xteBYxz8qSmU+FOByVExHrpVABfOplYKaVpdtueM3z5paN9xaoBnR23d7eq0NZ8AzqVLT6f+ogEVc+QKXdFuIaMFRS8DUUg++W1yjwtU9gENqZY94IkBfJUd1Eh2H0TV0wKWg=
    username: AgAbOO3c8AM5yerMFRjdck1fefnQ2Ng7nd2lW0UJQC3O75ym9jdY4p7wsUpTor4IiUs5BA9SR5l259aYwOf8RG7DbyMfVuwF2vRvDbSAPH5dIaVFUgY0QsrCS/i2EkAToXZAP17KnQuEK0Ey09V6jvJWIpfivwgAVSFGAXN7Yaswm1JnuCCDnnQasE1nacQS5ngwJHjCKFuffpd068+7XwxJN1BZcNDmczVsLMhFPldh25t9ieqVmReLuc7FHKOYKpRLAedmI6LYdmz/NG2UugzuPV5xC9bDZHgXePepY8k+wNMGWlTvuCli3VnNO9G35rcaL7EdnOvFJ0vDw58RYObUACGvzfku6UEXV5jdhQmPAgSar1gLKesruYpSrcA+fjyHqpA0jWUpO7w/zbG0FMjMRfapmIF/YqX38FvzkNZDrDONdjpViMQHP50Z+LG/dM8Tl9xqhps2chsMLer2o0SxnpP0NhViD62BXPDA21iOWyFS9zrChMgLcvWSLw814Ln3S68nWIoDm0VSzNOBgSG6qQOMZf19iVpCmV0JVK7GnZIRGFqBljKsQpCR5pJhwINfphZMoCcTBQmM8xSFq/qRSTqeFxJdxabZTv9zsWsWRUagbVDHB6hPKKTiKw/xJF7YabnrNvuWBMudonCkbyN54vM6q1E/PkIWFKPup23lsuoLlI7wBzSoYYRpLZcxixI/Wc/4kh0=
  template:
    metadata:
      name: postgresql-mlflow-user
      namespace: databases
