---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: databases
spec:
  encryptedData:
    password: AgBkv9vnur7keUXcbPu5FTaEf6jalF5thaZ5YMM2nWZ+H5CvZIoAXJXoLJdNfl+RjdVZuAybGZdAkUx6wmEWAfPweiB+4OAi75sXXkL4QHJmrFWI0jGV093XQ6iaIX3mdibNPbnNEAS+EckQrnS8PmfDLRCwDpYQwxRPVusI9xr8xzumM77wByECri+dJMv3NulKTZ77hkDkb0MBWvBBNxj4G5dgJRlv0HPY12odAGAKN+D5fki9iFwmo1e0eTLayRdX9LopV6LRRNcmysUa35IarrSTPzALuf6zVz0fFOvJgoj+dExjHk488Xyf/veSi3DIA54xT7sqBOEWcVYqlgDY2fDCkncRF4805bMc+6Gd/41DpsyYGVpMOQCpZHkDf64k7xltt1EcUyPC1rJRb5OWyOxFiEm73FuiP/xK3dUOrllMTAUfRXuMOceHwmdAqwb5BJoAI80laCb/P/uJHY8EstTgdIKBy7wUji1vdSJR6ulgJRwQ10pl6H+IIMytIc/ABz04VApKgM5JGqNK2tsGpTdqgGQK2DQyQzTNRCn/Yx8DqaQ/5XRa0PviqHrSNZnz2iBQ8g1OGI0C/h78UklsJNyjSH2UYxSKlV/GZ7ibII5fyfwoFuSWGpjPF+OeqOvE8mJzmkaPiSCpA6hdKXnhBoIQ0E7BwHUeTe+fOQicdZhNNQX3JxLhkgVKxmFiTSu/PTKhAY4UDFs+eckEtWL3390=
  template:
    metadata:
      name: redis
      namespace: databases
