---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ml-mlflow"
    tailscale.com/tags: "tag:k8s"
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: mlflow
