---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ml-airflow"
    tailscale.com/tags: "tag:k8s"
spec:
  ports:
    - name: airflow-ui
      port: 8080
      targetPort: 8080
  selector:
    component: webserver
    release: airflow
