---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBfysGjyU0bIyJIxPUkPA1/CVKbbp0UFck5kZaUrOLBlX7LMewDCfgNvnqvdRRDK3D8sgAyeTZSUbt1sldStqwULj45EwXbfgdjXhb3FhbM6LgGMLQrG1gvorXT3LAM4aONHP6A7TfYl24SmciUTPaWabE5pc2ewovlNVcSPjl9qRf2C4qh8midapyIZSarv0Y8gs0C2j0vw7xjn2JnaZrToHtlPc9dMkmzfj3j5oP1hXCIMUx9CQ8NM9X5bptKAgLXIFme+YYsh1Ru+ccDbgACl3RcySzE3XTqZHv2Vb8G/f0IaNh+mLl1UAVrZxpeqoKgqpbQjBjpb5+AkPzqT5djRSjWniLAuRvYotbHFrvR3tDOsv2GH8PBGBBseD+f17cM8ul7ICosBUdWdicTfwTq4gxBPqo1f0TKLgusa/MivUvghZbd1VKBJe7NtOc8+0yU5VFwIDQaeBQ+R/UgXqE4Qoe+rzESxtZO4SvMtOozeTR1XNXNSExbndjNrkRE0vzSHsmIrdU/lQrpx3EWYa3miR/dSNoz+biZn+vKX2RYMJS6Kl2XTEWcIhc4QmIezggLkb/Ga63NgNG5E7kz3YEr9iOc7KJhMlnTNlHkeEMztpZ4soCtX4+O4BsmOayEBtyl36bVXFtfTRhjWXESr+jr22rSSrYU4yJmnU5unbL0KTwcSf8ocGs2UUN4XswZf/Rfx+E9c1E2CgfdkIsSq2puzOWX4wQX6oazEPT3qA8=
    rootUser: AgACdCgOQDAsfUuWBthWVC3fsxFcT6XrgD5ZSXdY0pjkulL55yBIF/z5XvaUGLI6hWlhaEaUFCXeYC2ItuntnE+VhH9hkurLLVljVZaQRvSSV65TNEGAm51jOpUd0KNW9EG3pISlT7ILiXo7Mxc4Ep2P4ATLcS30S1MxeLKWFK6uJ3PMCWuDEZF+4LHQC9boPvQLku4lTYjGOCfdSaOQuwt4dbcEFxXiqQNLSbmpMUD792hM875y8iEwAFYuYCw9PMh3mmotK+QFznGDnkXT6PiNhen5lUZRLBm6HzxBP9KW+EfzWK+7jYN0JXDQNISvokB0lBbBHPP6SLIiZtQazqg8ukMiIUrGkLsB5wK959+waoNFIRy2nexp9W5UdxjGWnZuDdsAGpgEEKA9fOmUrgexIYWUh4Gj7qvVqs62LLFXt63xA7wfarM0j4ldwvIFl7x2UDiqwWyHLFrCfO41V3mZhdnOCRTdGdBoP61miyV6MBNhG8qPe3bT+eqRUun0PWPsMCAOp+c6RvCcqFe6zX085XTFNV1s2grhYmDH2NYc36nlq4JSOsxONphXetQZMlk+Q0d+82+5/wft/pEbROk2XyfU8oZ1LPdo8U8tfBZ6MWcaF92rYGl7n7PpEVVE7JnZ/q/FtPN/zf6LArPVUhYizBaFI8ofqO3x5wj+NN+SGmsuny5GG/qev2Z+9F7Gn2rpT5RaZQ==
  template:
    metadata:
      name: minio-root-credentials
      namespace: minio
