---
apiVersion: v1
kind: Service
metadata:
  name: airflow-external-postgresql
  namespace: airflow
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: airflow-external-postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-external-postgresql
  namespace: airflow
spec:
  serviceName: airflow-external-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: airflow-external-postgresql
  template:
    metadata:
      labels:
        app: airflow-external-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql-secret
                  key: password
            - name: POSTGRES_DB
              value: airflow
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 20Gi
