---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # External Secrets Operator Helm chart
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.9.11
      chart: external-secrets
      helm:
        values: |
          installCRDs: true
          serviceMonitor:
            enabled: false
          webhook:
            create: true
          certController:
            create: true
    # Custom configuration (ClusterSecretStore, etc.)
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/external-secrets/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
