---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # MetalLB Helm chart
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.3
      chart: metallb
      helm:
        values: |
          speaker:
            frr:
              enabled: false
    # Custom configuration (IPAddressPool, L2Advertisement)
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/metallb/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
