---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # MinIO Helm chart
    - repoURL: https://charts.min.io
      targetRevision: 5.0.15
      chart: minio
      helm:
        values: |
          mode: standalone  # or distributed for HA

          existingSecret: minio-root-credentials

          replicas: 1

          persistence:
            enabled: true
            size: 50Gi
            storageClass: nfs-client

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi

          service:
            type: ClusterIP
            port: 9000

          consoleService:
            type: ClusterIP
            port: 9001

          buckets:
            - name: mlflow
              policy: none
              purge: false
            - name: airflow
              policy: none
              purge: false
            - name: models
              policy: none
              purge: false
            - name: datasets
              policy: none
              purge: false

          # Users will be created via external secrets
          # See gitops/sealed-secrets/minio/ for user credentials
          users: []

    # Custom configuration
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/minio/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
