---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # MLflow - using community Helm chart
    - repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 0.7.19
      chart: mlflow
      helm:
        values: |
          image:
            repository: ghcr.io/mlflow/mlflow
            tag: "v3.7.0"

          serviceMonitor:
            enabled: false

          backendStore:
            postgres:
              enabled: true
              host: postgresql.databases.svc.cluster.local
              port: 5432
              database: mlflow
              user: mlflow
              password: "dummy"

          existingDatabaseSecret:
            name: mlflow-env-secret
            passwordKey: POSTGRES_PASSWORD

          artifactRoot:
            s3:
              enabled: true
              bucket: mlflow
              existingSecret:
                name: mlflow-env-secret
                keyOfAccessKeyId: AWS_ACCESS_KEY_ID
                keyOfSecretAccessKey: AWS_SECRET_ACCESS_KEY

          extraEnvVars:
            MLFLOW_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:9000"
            AWS_DEFAULT_REGION: "us-east-1"

          service:
            type: ClusterIP
            port: 5000

          ingress:
            enabled: true
            className: tailscale
            hosts:
              - host: ml-mlflow
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - hosts:
                  - ml-mlflow

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

    # Custom configuration
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/mlflow/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
