---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # kube-prometheus-stack (Prometheus + Grafana + Alertmanager)
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 56.0.0
      chart: kube-prometheus-stack
      helm:
        values: |
          prometheus:
            ingress:
              enabled: true
              ingressClassName: tailscale
              hosts:
                - ml-prometheus
              tls:
                - hosts:
                    - ml-prometheus
            prometheusSpec:
              retention: 15d
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    resources:
                      requests:
                        storage: 20Gi
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  cpu: 1000m
                  memory: 4Gi

          grafana:
            enabled: true
            adminPassword: admin
            ingress:
              enabled: true
              ingressClassName: tailscale
              hosts:
                - ml-grafana
              tls:
                - hosts:
                    - ml-grafana
            persistence:
              enabled: true
              size: 5Gi
              storageClassName: nfs-client
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
            additionalDataSources:
              - name: Loki
                type: loki
                url: http://loki.logging:3100
                access: proxy
                isDefault: false
                jsonData:
                  maxLines: 1000

          alertmanager:
            enabled: true
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    resources:
                      requests:
                        storage: 5Gi

    # Custom configuration (dashboards, rules, etc.)
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/monitoring/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
