---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # kube-prometheus-stack (Prometheus + Grafana + Alertmanager)
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 56.0.0
      chart: kube-prometheus-stack
      helm:
        values: |
          prometheus:
            service:
              annotations:
                tailscale.com/expose: "true"
                tailscale.com/hostname: "ml-prometheus"
                tailscale.com/tags: "tag:k8s"
            prometheusSpec:
              retention: 15d
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    resources:
                      requests:
                        storage: 20Gi
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  cpu: 1000m
                  memory: 4Gi

          grafana:
            enabled: true
            adminPassword: admin
            service:
              annotations:
                tailscale.com/expose: "true"
                tailscale.com/hostname: "ml-grafana"
                tailscale.com/tags: "tag:k8s"
            persistence:
              enabled: true
              size: 5Gi
              storageClassName: nfs-client
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi

          alertmanager:
            enabled: true
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    resources:
                      requests:
                        storage: 5Gi

    # Custom configuration (dashboards, rules, etc.)
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/monitoring/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
