---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # PostgreSQL Helm chart (Bitnami)
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.1.15
      chart: postgresql
      helm:
        values: |
          auth:
            enablePostgresUser: true
            existingSecret: postgresql
            database: postgres

          primary:
            persistence:
              enabled: true
              size: 20Gi
              storageClass: nfs-client

            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi

            # Environment variables for init script
            extraEnvVars:
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_DB
                value: postgres
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgres-password
              - name: MLFLOW_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-mlflow-user
                    key: password
              - name: AIRFLOW_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-airflow-user
                    key: password
              - name: MLWORKBENCH_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-mlworkbench-user
                    key: password

            initdb:
              scriptsSecret: postgresql-init-scripts

    # Custom configuration
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/namespaces/postgresql/overlays/local

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
