---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Sealed Secrets Helm chart
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: v2.18.0
      chart: sealed-secrets
      helm:
        values: |
          fullnameOverride: sealed-secrets-controller

          # Install CRDs
          crds:
            create: true

          # Resources
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

    # Custom configuration (sealed secret manifests)
    - repoURL: https://github.com/dverdonschot/mlworkbench.git
      targetRevision: main
      path: gitops/sealed-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
