---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCF9WLR97S/WTQQZguudSMRJyTmZWhxkBznJAc1GYGYmjByyzX+T3KE+yymkKZxMhaZ0rWsf+sLVHMd3rmCZ5AEjmV9iVfs+cMeHw0CYyRnPsnePxCgjRNwZrjoAPsHrwIlNMVKvDqbL2JAqgtoHGHt3/84xh5T8XQdzCbz9wAzWdfmy3lTxjN8sQoyjpvtf7hCb9k4hfWKyB9tynPy/4OcZoVFXRHYDLFMZrlPz6qqZnqA2c2Dd1/NXd83seiJcZMJiWkjvWqPfeP1eumwKUbfJMQ7u9XGIBfN4agViMYwy2ilrRDPMSgvNlftjW5p89IPNrKbYLi6Nm5QaQYn9bXfByzaiK7dXJAKCisjdLsJAPMeYYXwb/7o1ps4XWFpDWS5rB36Licwh+5HVsk1PqrK9yrhiH9GDY5zgAJ9q0JddbaRU74YOcKTx5DYRsE9H+KRiMjVwAjNfLL+TOixrcVb+prSB+5JAX9uvb536E9DtxcXosgtyNLXqvS4+uuqaA1SmRZEsk9Z0mSelizZByShYngZHFmawd55LE+INRyjP+yTPg2yVM+TcVHX3u21+p5joWg8Qax23vAgi2Hu2nZWKDjY2/HEetWcz5hhPmw9t72JTGjdCkJ16AzjzuUmph7xr+r60eENo/HbLVncxPnsNCnaI+z1i5ruM04uMpRlF6j2YGZpwP66roJpaafEKFj0N+ewGsezt9JhALpovNVpYg==
    client_secret: AgA+XMYJPdV2+Seu6iPiXqtmQSQcbXPPXiL7NIZMMaBGjCREXEv7NUqMEyNdUs9Culornu9dCaiqe/TnAeQQ0m/C3tfa0M6tXV1YEzxayOvbKs50Q4j2mXnwQx5eIvl3T70q9HnMJ2Dlo2YOdVhwy84f2lZ6vFKOiBXtMtB06ZJHMGZ2G8HSVQRcxfTou5sSgMyPJ5LURn6UNLIwlx8kxWUWcAM1hF1iVWOgtd9qIuxNavbh2sTWCqs5/WCCTXyxQpk7xKIEuRagbPioUoCzqRZFbjks/AAiMZ017Rof59SomH4Tj0FlEEP+qsooWz5W4Xjr+Ll8CFeeDfoLpSm531noOS00hYlHIMZHpPjA90HklduSfCNhxY8lg7hXjfwEX9+HfH5Q3sXnr+vHnSfXGNL1FokhulM+rTR1mrFwa930/fXHGtyJPnYg2+/K7YPpq/ePPSzk/FuhOGq5UkOWNypzGpjc9il4w+/c2Ta3NEFw6cyJuKHwGDv7Tk93k3vJ791Fd9+e2jc2xOVuU+eEbd2kwfwuG8Yg6yU3xa0fUeiuqanQS0gPmHSlY4oK94TPAwh5j9aVi8yeLRWqFJR+OSKPQ+iFcO7jANhbAawfrJLXmp3ovbJIAjZdJ8r/vSouCQ5i+KmtYTNw/3MxcuZ1Z79z3vdNbjs01Ba2cbZzbGDaQpNjbULw1tAq6fIYZCBizXRknECDyFkmJlD2Ln2G/5gcZLN5mqKo2Ezp9b1oclmawumuLz5dbtfXf/kd6kavYmZpej1ceLJWJv9fd/qr
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
