---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCOpqiGm5nQoG1TtbX/zRPJzUr1z7X027kZV6F0ZpkaN8xv/KIHwmzKs3FP+cxbyMFSDmQG4HJxIgHl9jvhwDo95eN/MzGFV3tY+yyMOJg0WREg7BJVrSyRaYUdy4TZpMZHcNxr7Ek2NYY1I4R/yVTZW3RDnnHJTDhE4SoQ4dYVr5BbVYi2kUeZzJPRzavC6q3MHq5XvyaEO0iG0UIHFOw5C3WS9kNPA0tfGTY3QYmQEB4Jc7htvgEAT3FkXf2NLd0jD6y7w5aXFQRX01OuAlh38F+ONRvlQzYmIGaxfb0IqmpZnnXGW+EE9TcTpJALJDx8NTWXGDLPd1Az65/UJhC8Gq+kDwEgDFSLpnYGdtFWQnd7S4K+VLnJbHLYNtSH8RPbrEX+K/JzAv+JqsRGvov3IsddeOmRucRvpLO1ltwn+prS6Gu9IhX/54s7RN4hM3hp/QIRZy4Yi5c59fvlz9m7OQuvdRpieAihmgOBP8ivaZRToi/pDkJqFZB446wY+DrWdA8J/JDw7zxagSYP0HSp7kJOhsnXHF4/UpaSjGvFLAcy3GysB+y81zkwnRFzSw0o+WZz++DTQnn5l1t61P94mOQx6f1CxVpkJZ0z1SRsLFFCKG3aiOV8iSagATmCkEhsqsWfIgnhITK9TOPJ2vxsStxHD+5iuPDdlkbSRzhUMLe2S3Y5Ti0n8n/+iGQi3fDefKrzML++E7qdYfOLbJGA6g==
    client_secret: AgCIZK1k68Dxvk+0Rh6bRhQ8t4ztQ//KSIL0HvqaEoISeMmUSJEQ6hF/xx1i5caemUzYZJP3RI0Ry25KeiLbTX1iLpWGLQ3LGusEkyLA3gVx4ipdjLoSj6KjZTo9RqZNVc786WmZZZ+NUW1UAYxbVzZPYynQQOZqHKqZ5DQQEQ92g4JngdfQzVRFICW0YkZKI4n7fIbq+RqxLPoOM1iDtlYo+/GmwaXSzUyL4/Kzk+T90cJy3aMA3xfttcgPECjo1zwsGbXpkGatumVGaGxiYxIR3BhdBjtyDWDKbNyYvADTNLk4As9/BldLpiFheTf+UW2wRPz/HrttTkPiufAftG8SELFjcvGkLesohESHOMdEvxvEDSl6OZojJUa7p9A2SKai8rJ0R5EVVnS3AOwowWefg0pzieHfVLhX1W/TXfS84YxNI6H2f/60NNuGMB6UNRAwOSlQA8K4XrKkaDJi4IOLCk7oYtW1AL5W/sl3jIbu8F0I1i2Ouc44VjniSNBXWIEOJqiYdMV++5rGAwtZOSQQOL+goxo+XROa7O5uyrCep57VxBqx8I7oldj/t6boT/e6PHrZ0pSDJBqQrloOlEh8ZoOLZ+6dTZHt1kNw/CmDy2vdx9eTfULP+WjjodN6cxKBXBpz+sn06QzU2xqUljujrEjZ0OT0BB1I7Naz8RdEuEwSKQFVIS0tBDx05jyFZVIl7eguR8sfSRYR3UY5qAU2VKMM2FZ0DS1glx3NpCPPSyJybAHNTU4K1PlRa9yTZMAmGQyxLj/TdjApn53bgDYg
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
