---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBs5/vnyptVMnAn4y3UXq3ByWr54thS+wwGx+h6PR0P9PobAZzTSgPePOuA9WKrQuOD8miXrAt13Q2hjjVi8PuYENUAKGmYw0Hzjc7hPKkAzcNnzJTcT54Z3P9nHrzcdMHI5LXdYZ0+Gjbb6crZkn9vA5G0+Y8zZRAYp6PLdEvUVaRRMsS4qJ2UXkMcb+er6Wkmh9Jmrtd9biIlIiF32W1nbsEJG74+Y8fJStoeAJm3sTOe8+pthk07f8JQ3raZxnzdAwCqEqBgO/L3Z81dEPqmRbMyd9gVZdrR27P2L03m1+9z8ra+HgDwEbGtTAuo15S4kmwqdg5AIYD3dnTqaxErW9ZQqcIKmr+tCsurFWNKR9Ljup7QAo0ccNI4rlVbsMTx6q04+771wvETa4r4I2jrwgwgRqIZPqdmAgwvfuRAn+ErVHdCMRN4g0lZqFg2HkAVdUCutzrU/q/P0mocJdb3+QuJIo5naqB//WkyhQBqEJkY+m+MH5YQ1srbgiGJI7opa9ISfRt3HjhsDbC3mBjYKZUU6AnZIqgjzzT3zhbuuUBcUuafQ1Yl/S4lLH3w7jY0s4Oy6vN2JYw/z1z+fS/3Od295csSdROpUIiyWIgVtLFnWKQ7SV5WSL0UaabvSvGAcyox0UUML/SddXGXBD3tqlJcnHvzgdfl4hGzh37c2OI47OX0Bw26+Cr7ndU/wHMCSy5JELbgnpAsQvBnBhzd3w==
    client_secret: AgA/csLkv3tYGVzCJnZLaiFv5/IN7oYqzEKPYug61b/BurEJ+YasAq43tCqw+yGOO+WhymanjGiIlNLBgoPuBP7t9hib4t3fFpH/5xUuzfIk3x3vo91LcyrcjeA3gwMqWanxwrcqWIMB8a/3RlLilab0AXpQH3cWVzrh6LmlbfJsjf4wRbvb7DPqPnCXI22If3iXM9er7LqdrHnaBXVXixJ51WdU7caVIrBn1WE6WNGRrCV8viZlYgfSz+CSlHJkb189cy9IYCbzbhrzIoZmqkKPiZuyhM8BUa6+QNNU4xQqpjQJgVwfKDxfUakS5E5aM+VkT+pLzDYtQwi0CNAKMijSkF6TjHAZUvkxSZqbwTGa3UeXbRG0oRy8vT8Z3xBeIoQCf1FfzbZBWwsmYeUH4QIQOj60TgwH5pHsO5u6YhAFrl8uOARAAtxnjfE/qxFrdKSItVYA/yGFkx5jDMfjnV5Zoj/d8gGS1Fohu9hcy6kMDkbUrW61DejO1Mvg1tWce3ql80NP1ZISP5ETFyIAd0ZZYK+XnQRnsfnc9MeElVKQetMDXq7RV72Y20otjsgTMjUeAVBKP8hxAAue9Bf/YWLAtnJWWwntnHkATbz/U6ubWMGhHARIdjBAjeVJzNIZJlysZTmmfmMAZF/Vh0AF9JRG5YP4UecicqSTzN8GaKp5xj5G9NXk0qfz1UMnQylayjCAOj3sK1p7R//FFDVSOEuEU2f2aCY2fNhNfAoUIMCTVd8TkPMUYB+I7Q+eq9lx6mPGB/DfhlPg5fLXg7nN
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
