---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "ml-argocd"
    tailscale.com/tags: "tag:k8s"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
